%{
#include "hpp.hpp"
string LexString;
%}
%option noyywrap
%option yylineno
%x lexstring
%%
#[^\n]*			{}

'				{BEGIN(lexstring); LexString="";}
<lexstring>'	{BEGIN(INITIAL); yylval.o=new Str(LexString); return STR;}
<lexstring>\\t	{LexString+='\t';}
<lexstring>\\n	{LexString+='\n';}
<lexstring>\n	{LexString+=yytext[0];}
<lexstring>.	{LexString+=yytext[0];}

[a-zA-Z0-9_.]+	TOC(Sym,SYM)

[ \t\r\n]+		{}
%%